### PR TITLE
docs: Add EIP-1167 minimal proxy section

### PR DESCRIPTION
**Pull request by aefhm**
## Description

Close https://github.com/oasisprotocol/sapphire-paratime/issues/350 by noting full support.

### CODE REVIEW

**Comment by rube-de** [comment]
do we want to mention that the explorer will detect them?
or wait with it until it will also show verified?

**Comment by aefhm** [comment]
> do we want to mention that the explorer will detect them?

I think this is expected behavior? Or do you mean that we should note that Explorers only detect after a proxy transaction?

> or wait with it until it will also show verified?

My first thought was to call out Sapphire differences only. 🤔

**Review by rube-de — APPROVED** [review]
Ok, I thinks it's fine like this. 
Initially I thought it could raise question for devs when they don't see it as proxy directly, but as the ticket for the Explorer is still open, I hope this will be fixed.

**Comment by aefhm** [comment]
> Initially I thought it could raise question for devs when they don't see it as proxy directly,

I do find this to be an issue. I believe the other proxy contracts also aren't picked up correctly by the Explorer until a transaction is made. I wonder if this page or perhaps a new one is a better place for quirks with our Explorer.

> but as the ticket for the Explorer is still open, I hope this will be fixed.

Agree that the Explorer UI is the _**best**_ place to convey this information.

**Pull request merged**
