### PR TITLE
bump oasislabs/hardhat to 2.16.1

### PR DESCRIPTION
**Pull request by xmzheng**
bump the oasislabs/hardhat version so it should be compatible with hardhat 2.16.1

### CODE REVIEW

**Review by CedarMist — COMMENTED** [review]
The https://github.com/oasislabs/hardhat repo hasn't changed while a new version of @oasislabs/hardhat has been pushed up to npmjs for 2.16.1.

Does the oasislabs/hardhat repo represent what's on npmjs?

**Comment by xmzheng** [comment]
> The https://github.com/oasislabs/hardhat repo hasn't changed while a new version of @oasislabs/hardhat has been pushed up to npmjs for 2.16.1.
> 
> Does the oasislabs/hardhat repo represent what's on npmjs?

the correct repo is: https://github.com/oasislabs/NomicFoundation-hardhat/blob/main/packages/hardhat-core/package.json#L3

**Review by CedarMist — APPROVED** [review]

**Comment by CedarMist** [comment]
When this is merged we will be compatible with Hardhat 2.16.

People using previous versions must upgrade their project to Hardhat 2.16

**Review by CedarMist — APPROVED** [review]
So now the integrations/hardhat (@oasisprotocol/sapphire-hardhat) package will track the minimum version of hardhat that it's targeting.

**Pull request merged**
